export const initialBooking = {
  idbooking: "1",
  idSchedule: "",
  idCustomer: "",
  idVoucher: "1",
  paymentOption: "",
  bookingTime: "",
  total: "",
  sstBooking: "",
  AmountPeople: "",
  tourTimeStart: "",
  PhoneNumber: "",
  Reservationist: "",
  disCount: "",
};
